// <auto-generated />
using CoreAndFood.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoreAndFood.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220512164313_ssss")]
    partial class ssss
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CoreAndFood.Data.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminID"), 1L, 1);

                    b.Property<string>("AdminRole")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AdminID");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdminID = 1,
                            AdminRole = "A",
                            Password = "1234",
                            UserName = "Mikdat"
                        });
                });

            modelBuilder.Entity("CoreAndFood.Data.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"), 1L, 1);

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryDescription = "Tazeliğine güveniyoruz",
                            CategoryName = "Meyveler",
                            Status = false
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryDescription = "Organik mahsüller",
                            CategoryName = "Sebzeler",
                            Status = false
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryDescription = "Olmazsa olmazlarımız",
                            CategoryName = "Bakliyat",
                            Status = false
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryDescription = "E kuru kuru gitmez",
                            CategoryName = "İçecekler",
                            Status = false
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryDescription = "Ufak bir kaçamak vakti...",
                            CategoryName = "Tatlılar",
                            Status = false
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryDescription = "Eğlence ortamının vazgeçilmezleri:)",
                            CategoryName = "Atıştırmalıklar",
                            Status = false
                        });
                });

            modelBuilder.Entity("CoreAndFood.Data.Models.Food", b =>
                {
                    b.Property<int>("FoodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodID"), 1L, 1);

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("FoodID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            FoodID = 1,
                            CategoryID = 1,
                            Description = "",
                            ImageURL = "https://e7.pngegg.com/pngimages/740/778/png-clipart-apple-apple-fruit.png",
                            Name = "Elma",
                            Price = 6.0,
                            Stock = 100
                        },
                        new
                        {
                            FoodID = 2,
                            CategoryID = 1,
                            Description = "",
                            ImageURL = "https://img2.pngindir.com/20180920/kv/kisspng-orange-juice-orange-juice-citrus-sinensis-food-th-sweet-melody-1-bio-certifi-ecocert-sp-5ba39c39e57a95.18511885153744901794.jpg",
                            Name = "Portakal",
                            Price = 7.0,
                            Stock = 140
                        },
                        new
                        {
                            FoodID = 3,
                            CategoryID = 2,
                            Description = "",
                            ImageURL = "https://img2.pngindir.com/20180306/jve/kisspng-roma-tomato-food-beefsteak-tomato-clip-art-tomato-5a9e89af05cba3.5844826615203393750238.jpg",
                            Name = "Domates",
                            Price = 5.0,
                            Stock = 170
                        },
                        new
                        {
                            FoodID = 4,
                            CategoryID = 4,
                            Description = "",
                            ImageURL = "https://img2.pngindir.com/20180713/gtb/kisspng-fizzy-drinks-uluda-gazoz-iced-tea-uluda-gazoz-gazoz-5b48ba36176547.5424333815314929180958.jpg",
                            Name = "Gazoz",
                            Price = 7.0,
                            Stock = 85
                        },
                        new
                        {
                            FoodID = 5,
                            CategoryID = 3,
                            Description = "",
                            ImageURL = "https://e7.pngegg.com/pngimages/1/530/png-clipart-rice-rice-thumbnail.png",
                            Name = "Pirinç",
                            Price = 11.0,
                            Stock = 110
                        },
                        new
                        {
                            FoodID = 6,
                            CategoryID = 2,
                            Description = "",
                            ImageURL = "https://e7.pngegg.com/pngimages/540/261/png-clipart-potato-potato.png",
                            Name = "Patates",
                            Price = 4.0,
                            Stock = 150
                        },
                        new
                        {
                            FoodID = 7,
                            CategoryID = 4,
                            Description = "",
                            ImageURL = "https://img2.pngindir.com/20180702/rej/kisspng-apple-juice-apple-cider-orange-juice-smoothie-5b3aa3360fbe52.7272249515305695260645.jpg",
                            Name = "Elma Suyu",
                            Price = 9.0,
                            Stock = 180
                        },
                        new
                        {
                            FoodID = 8,
                            CategoryID = 5,
                            Description = "",
                            ImageURL = "https://e7.pngegg.com/pngimages/975/423/png-clipart-chocolate-dessert-profiteroles-food-french-pastries.png",
                            Name = "Profiterol",
                            Price = 16.0,
                            Stock = 75
                        },
                        new
                        {
                            FoodID = 9,
                            CategoryID = 6,
                            Description = "",
                            ImageURL = "https://w7.pngwing.com/pngs/325/140/png-transparent-chips-screenshot-french-fries-fish-and-chips-potato-chip-junk-food-chips-pic-food-baking-fruit.png",
                            Name = "Cips",
                            Price = 8.0,
                            Stock = 65
                        },
                        new
                        {
                            FoodID = 10,
                            CategoryID = 6,
                            Description = "",
                            ImageURL = "https://media.istockphoto.com/photos/industrial-sweet-biscuit-picture-id869217802?k=20&m=869217802&s=170667a&w=0&h=HmF5q4fyWHCUh9wYyHfYN-kuLaZO7mVLRs2wvAz5fhA=",
                            Name = "Bisküvi",
                            Price = 4.0,
                            Stock = 140
                        },
                        new
                        {
                            FoodID = 11,
                            CategoryID = 5,
                            Description = "",
                            ImageURL = "https://maksatbilgi.com/wp-content/uploads/2021/08/kazandibi-tarifi-one-cikan.jpg",
                            Name = "Kazandibi",
                            Price = 12.0,
                            Stock = 60
                        });
                });

            modelBuilder.Entity("CoreAndFood.Data.Models.Food", b =>
                {
                    b.HasOne("CoreAndFood.Data.Models.Category", "Category")
                        .WithMany("Foods")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CoreAndFood.Data.Models.Category", b =>
                {
                    b.Navigation("Foods");
                });
#pragma warning restore 612, 618
        }
    }
}
